alias la='ls -a'
alias ll='ls -alh'
alias c='clear && figlet TuX'
alias h='rm ~/.bash_history'
alias s='suspend'
alias py='python'
alias cdc='cd ..'
alias rs='setxkbmap rs'
alias figlet='figlet -t'
alias wakecomp='wakeonlan 00:1D:92:74:DF:8B'
alias AMD='DRI_PRIME=1'
alias open='xdg-open'
alias adb='/data/Android/Android/opt/android-sdk/platform-tools/adb'
