alias la='ls -a'
alias ll='ls -alh'
alias c='clear && figlet TuX'
alias p='cd ~/Python'
alias viber='/opt/viber/Viber'
alias h='rm ~/.bash_history'
alias s='suspend'
alias py='python'
alias t='cat .tux.txt'
alias cdc='cd ..'
alias rs='setxkbmap rs'
alias figlet='figlet -t'
alias wakecomp='wakeonlan 00:1D:92:74:DF:8B'
alias in='sudo apt install'
alias AMD='DRI_PRIME=1'
alias firefox='/home/hawerner/Downloads/firefox/firefox'
